language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "10"
matrix:
    include:
         - node_js: "6"
           arch: ppc64le
         - node_js: "10"
           arch: ppc64le
